### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'bone'

### ISSUE THREAD

**Issue by muskanasmath** [Uason-Chen/CTR-GCN#37]
Hi, I'm a university Student. This repo has really helped me understand how to implement GCN for skeleton based action recognition using smaller dataset for my limited resources. After training for UCLA dataset using below command and adding "bone motion in data path in config:

       python main.py --config config/ucla/default.yaml --work-dir work_dir/ucla/ctrgcn_xxx --device 0

I used the below command for testing but got error that I'm unable to debug:

        python main.py --config work_dir/ucla/ctrgcn_xxx/config.yaml --work-dir work_dir/ucla/ctrgcn_xxx --phase test --save-score True --weights work_dir/ucla/ctrgcn_xxx/runs-54-17172.pt  --device 0

Kindly please help me understand and resolve the issue. Below is the complete error:

[  ] Load weights from work_dir/ucla/ctrgcn_xxx/runs-54-17172.pt.
[  ] using warm up, epoch: 5
Traceback (most recent call last):
  File "main.py", line 576, in <module>
    processor = Processor(arg)
  File "main.py", line 237, in __init__
    self.load_data()
  File "main.py", line 263, in load_data
    dataset=Feeder(**self.arg.test_feeder_args),
TypeError: __init__() got an unexpected keyword argument 'bone'

**Comment by muskanasmath** [comment]
Hi, I'm facing the same issue. Please elt me know if you could resolve it. Thank you.
